# 데이터 수집 및 전처리

### [활용 데이터]

- 1.[상권영역] 서울시 상권분석서비스(영역-상권) 2023.10월 기준
https://data.seoul.go.kr/dataList/OA-15560/S/1/datasetView.do

- 2.[개폐업 수] 서울시 상권분석서비스(점포-상권),
[프랜차이즈 수] 서울시 상권분석서비스(점포-상권) 2019~2022 기준
https://data.seoul.go.kr/dataList/OA-15577/S/1/datasetView.do

- 3.[매출금액] 서울시 상권분석서비스(추정매출-상권) 2019~2022 기준
https://data.seoul.go.kr/dataList/OA-15572/S/1/datasetView.do

- 4.[길단위인구 수] 서울시 상권분석서비스(길단위인구-상권) 2019~2022 기준
https://data.seoul.go.kr/dataList/OA-15568/S/1/datasetView.do

In [1]:
# 필요한 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
# 한글 폰트 깨짐 현상 해결(jupyter notebook)
plt.rcParams['font.family'] = 'Malgun Gothic'
# 마이너스 부호 출력 설정
plt.rcParams['axes.unicode_minus']=False

# 한글 폰트 깨짐 현상 해결(Colab)

## 1.상권영역 데이터 전처리
- 서울시 상권영역: 1650개 (2023년 기준)

In [3]:
# 파일 읽어오기, 한글csv file이므로 encoding cp949
commer_district = pd.read_csv('./data/commer_district.csv', encoding='cp949')
commer_district

,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,자치구_코드,자치구_코드_명,행정동_코드,행정동_코드_명,영역_면적
0,A,골목상권,3110008,배화여자대학교(박노수미술관),197093,453418,11110,종로구,11110515,청운효자동,149264
1,A,골목상권,3110009,자하문터널,196991,455057,11110,종로구,11110550,부암동,178306
2,A,골목상권,3110010,평창동서측,197064,456643,11110,종로구,11110560,평창동,369415
3,A,골목상권,3110017,정독도서관,198581,453781,11110,종로구,11110600,가회동,83855
4,A,골목상권,3110018,중앙고등학교,198883,453690,11110,종로구,11110600,가회동,166872
...,...,...,...,...,...,...,...,...,...,...,...
1645,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,198397,451614,11140,중구,11140520,소공동,983618
1646,U,관광특구,3001493,동대문패션타운 관광특구,200996,451976,11140,중구,11140590,광희동,606058
1647,U,관광특구,3001494,종로?청계 관광특구,199796,452274,11110,종로구,11110615,종로1?2?3?4가동,653127
1648,U,관광특구,3001495,잠실 관광특구,210188,446334,11710,송파구,11710562,방이2동,2462734
1649,U,관광특구,3001496,강남 마이스 관광특구,205282,445736,11680,강남구,11680580,삼성1동,237892

In [4]:
# 상권_코드, 상권_코드_명 칼럼만 남기고 전부 삭제
commer_district.drop(commer_district.columns[4:11], axis=1, inplace=True)
commer_district.drop(commer_district.columns[0:2], axis=1, inplace=True)

# 합친 파일 저장
commer_district.to_csv('../gentrification/data_finish/commer_district_finish.csv', index=False)
commer_district

        상권_코드                 상권_코드_명
0     3110008         배화여자대학교(박노수미술관)
1     3110009                   자하문터널
2     3110010                   평창동서측
3     3110017                   정독도서관
4     3110018                  중앙고등학교
...       ...                     ...
1645  3001492  명동 남대문 북창동 다동 무교동 관광특구
1646  3001493            동대문패션타운 관광특구
1647  3001494              종로?청계 관광특구
1648  3001495                 잠실 관광특구
1649  3001496             강남 마이스 관광특구

[1650 rows x 2 columns]

## 2.개폐업수 데이터 전처리
- 2019~2022 프랜차이즈수, 개폐업수 파일 합치기

In [5]:
# 프랜차이즈수, 개폐업수 파일 전부 읽어오기, 한글csv file이므로 encoding cp949
fran_openclose_2019 = pd.read_csv('./data/fran_openclose_2019.csv', encoding='cp949')
fran_openclose_2020 = pd.read_csv('./data/fran_openclose_2020.csv', encoding='cp949')
fran_openclose_2021 = pd.read_csv('./data/fran_openclose_2021.csv', encoding='cp949')
fran_openclose_2022 = pd.read_csv('./data/fran_openclose_2022.csv', encoding='cp949')
fran_openclose = pd.concat([fran_openclose_2019,fran_openclose_2020,fran_openclose_2021,fran_openclose_2022])

# 합친 파일 저장
fran_openclose.to_csv('../gentrification/data_finish/fran_openclose_finish.csv', index=False)
fran_openclose

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20191,R,전통시장,3130018,동대문문구완구거리(동대문문구완구시장),CS300043,전자상거래업,10,10,10,1,0,0,0
1,20191,D,발달상권,3120165,서래마을카페거리(서래마을),CS100007,치킨전문점,0,1,0,0,100,1,1
2,20191,D,발달상권,3120177,신논현역 1번,CS300015,가방,3,3,0,0,0,0,0
3,20191,A,골목상권,3110508,서연중학교,CS200041,사진관,6,6,17,1,0,0,0
4,20191,A,골목상권,3110241,먹골역 5번,CS300036,조명용품,2,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304750,20224,A,골목상권,3110631,방화초등학교,CS200038,독서실,0,0,0,0,0,1,0
304751,20224,A,골목상권,3110954,국기원,CS200010,변호사사무소,0,0,0,0,0,1,0
304752,20224,A,골목상권,3110687,"천왕역 3번(오류2동주민센터, 서울오류남초등학교)",CS100008,분식전문점,0,0,0,0,0,1,0
304753,20224,R,전통시장,3130054,황학동주방가구거리상점가,CS200034,여관,0,0,0,0,0,1,0
304754,20224,A,골목상권,3110135,성동세무서,CS200003,예술학원,0,0,0,0,0,1,0

## 3. 매출액 데이터 전처리
- 2019~2022 매출액 파일 합치기

In [6]:
# 매출액 파일 전부 읽어오기, 한글csv file이므로 encoding cp949
money_2019 = pd.read_csv('./data/money_2019.csv', encoding='cp949')
money_2020 = pd.read_csv('./data/money_2020.csv', encoding='cp949')
money_2021 = pd.read_csv('./data/money_2021.csv', encoding='cp949')
money_2022 = pd.read_csv('./data/money_2022.csv', encoding='cp949')
money = pd.concat([money_2019,money_2020,money_2021,money_2022])

# 합친 파일 저장
money.to_csv('../gentrification/data_finish/money_finish.csv', index=False)
money

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_금액,...,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수
0,20191,D,발달상권,3120037,동대문역사문화공원역,CS200029,네일숍,20393290,208,17051978,...,86,27,0,208,0,56,21,0,123,8
1,20191,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,CS200029,네일숍,73147711,2136,57025458,...,1270,35,59,2077,0,715,995,236,157,33
2,20191,A,골목상권,3110085,경리단길남측,CS200029,네일숍,3000000,40,2337081,...,14,9,0,40,0,8,28,5,0,0
3,20191,A,골목상권,3110166,구의1동주민센터,CS200029,네일숍,8443798,153,4984275,...,64,13,13,140,0,52,88,13,0,0
4,20191,A,골목상권,3110161,중곡역 3번,CS200029,네일숍,20756990,305,16694436,...,196,36,4,301,0,79,28,68,91,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83568,20224,R,전통시장,3130051,동화동 골목형상점가,CS100010,커피-음료,74566607,11618,46002960,...,811,56,4239,7016,41,1539,2107,2831,2696,2037
83569,20224,A,골목상권,3110121,한양대역 4번,CS100010,커피-음료,496341232,74976,343713652,...,22056,9747,37372,37498,6632,45799,6409,5767,9168,1094
83570,20224,A,골목상권,3110163,성자초등학교,CS100010,커피-음료,60999234,10668,39994099,...,2205,349,5054,5440,212,2459,2483,2900,1459,980
83571,20224,A,골목상권,3110110,상왕십리역 6번,CS100010,커피-음료,35826724,4681,17309483,...,361,0,1811,2870,0,1966,1784,672,155,104
83572,20224,D,발달상권,3120065,회기역,CS100010,커피-음료,340596205,67496,206793777,...,16780,1930,33303,33800,1141,29609,16899,8442,8130,2883

In [7]:
# 모든 칼럼이 보이지 않아서 칼럼을 바꿈
money.transpose()

,0,1,2,3,4,5,6,7,8,9,...,83563,83564,83565,83566,83567,83568,83569,83570,83571,83572
기준_년분기_코드,20191,20191,20191,20191,20191,20191,20191,20191,20191,20191,...,20224,20224,20224,20224,20224,20224,20224,20224,20224,20224
상권_구분_코드,D,U,A,A,A,D,R,A,D,A,...,D,R,A,D,A,R,A,A,A,D
상권_구분_코드_명,발달상권,관광특구,골목상권,골목상권,골목상권,발달상권,전통시장,골목상권,발달상권,골목상권,...,발달상권,전통시장,골목상권,발달상권,골목상권,전통시장,골목상권,골목상권,골목상권,발달상권
상권_코드,3120037,3001492,3110085,3110166,3110161,3120072,3130147,3110438,3120158,3110850,...,3120024,3130182,3110591,3120056,3110043,3130051,3110121,3110163,3110110,3120065
상권_코드_명,동대문역사문화공원역,명동 남대문 북창동 다동 무교동 관광특구,경리단길남측,구의1동주민센터,중곡역 3번,성신여대,쌍문역동측상점가,경춘선숲길 우측,녹두거리(대학동),사당역 10번,...,회현역,영천시장,충정로역 6번,구의역,충무초등학교,동화동 골목형상점가,한양대역 4번,성자초등학교,상왕십리역 6번,회기역
서비스_업종_코드,CS200029,CS200029,CS200029,CS200029,CS200029,CS200029,CS200029,CS200029,CS200029,CS200029,...,CS100010,CS200001,CS100010,CS100010,CS100010,CS100010,CS100010,CS100010,CS100010,CS100010
서비스_업종_코드_명,네일숍,네일숍,네일숍,네일숍,네일숍,네일숍,네일숍,네일숍,네일숍,네일숍,...,커피-음료,일반교습학원,커피-음료,커피-음료,커피-음료,커피-음료,커피-음료,커피-음료,커피-음료,커피-음료
당월_매출_금액,20393290,73147711,3000000,8443798,20756990,122719691,11384929,3542727,27950110,25952543,...,663360129,3287672,23208485,717270334,126493832,74566607,496341232,60999234,35826724,340596205
당월_매출_건수,208,2136,40,153,305,1931,173,55,380,548,...,45590,16,5104,111612,22085,11618,74976,10668,4681,67496
주중_매출_금액,17051978,57025458,2337081,4984275,16694436,89162313,9896703,2448866,14764854,18495846,...,559002499,1643836,18042474,515200032,108671002,46002960,343713652,39994099,17309483,206793777
주말_매출_금액,3341312,16122253,662919,3459523,4062554,33557378,1488226,1093861,13185256,7456697,...,104357630,1643836,5166011,202070302,17822830,28563647,152627580,21005135,18517241,133802428
월요일_매출_금액,10079574,11704014,0,0,245090,26614604,2852434,468093,0,2083206,...,91695939,0,2802978,92408324,19259973,6888550,69315709,6442356,5314656,43748492
화요일_매출_금액,0,9926780,604671,0,565445,7864674,2480376,650403,4241514,8279899,...,123457387,0,4358971,102129557,23365559,8896483,73849753,7478408,3331034,33290528
수요일_매출_금액,3251302,13925573,294118,1306931,3744146,25560090,0,0,1045752,2052313,...,111643724,0,3233875,103489613,20349013,9061363,72567043,6236560,3698276,41681155
목요일_매출_금액,1736638,11094589,705882,2370413,3384050,9579703,4563893,0,3510218,2624664,...,123027677,0,3363859,102129354,21537034,8667861,58950905,9338456,0,42157184
금요일_매출_금액,1984464,10374502,732410,1306931,8755705,19543242,0,1330370,5967370,3455764,...,109177772,1643836,4282791,115043184,24159423,12488703,69030242,10498319,4965517,45916418
토요일_매출_금액,596831,12816251,477734,2754805,3355372,11426794,1488226,1093861,12746479,5572262,...,77236362,1643836,3327673,121664263,11069638,9673626,77055692,11736075,9129309,71510636
일요일_매출_금액,2744481,3306002,185185,704718,707182,22130584,0,0,438777,1884435,...,27121268,0,1838338,80406039,6753192,18890021,75571888,9269060,9387932,62291792
시간대_00~06_매출_금액,0,0,0,0,0,0,0,0,0,0,...,8832833,0,0,2516019,0,0,41427233,0,0,0
시간대_06~11_매출_금액,0,71676,555556,0,0,0,0,0,0,0,...,46854841,0,6351100,82299310,18486204,19477214,25001171,8264684,5211208,42395036
시간대_11~14_매출_금액,2806361,13593203,185185,1153174,2372621,11092643,0,640549,4724169,1698487,...,246478921,0,6641538,223269056,62892129,33773830,102446489,19249803,14676724,96629651
시간대_14~17_매출_금액,1883718,18551907,826252,1588818,3714210,49133529,5903297,1034733,9331328,5757493,...,98555254,1643836,4042820,162081669,26978650,15634962,120403016,19200891,12990517,100395110
시간대_17~21_매출_금액,14209451,39329730,1026528,4420501,12054755,43601473,1289796,881986,12578281,17235124,...,126708562,1643836,3929502,202776540,16792225,5287095,143669294,12358695,2948275,88316784
시간대_21~24_매출_금액,1493760,1601195,406479,1281305,2615404,18892046,4191836,985459,1316332,1261439,...,135929718,0,2243525,44327740,1344624,393506,63394029,1925161,0,12859624
남성_매출_금액,0,3011932,0,128130,419890,11059396,5531240,147819,3451714,576657,...,243593388,0,11755316,324304110,52609872,26781662,242544309,26777473,14405172,160395118
여성_매출_금액,20393290,70135779,3000000,8315668,20337100,111660295,5853689,3394908,24498396,25375886,...,241043712,3287672,10025255,365656059,67073874,44278812,252937137,31591325,21421552,170671945
연령대_10_매출_금액,0,0,0,0,0,3940341,0,0,0,154462,...,1393040,0,158659,11639482,6517207,241241,46431059,1759271,0,5064572
연령대_20_매출_금액,3494505,20258941,479303,1716948,4348966,57826170,5754473,650403,13170631,3863823,...,74146240,0,4516529,223115003,43317476,6988868,290772811,13866873,14599137,135343508
연령대_30_매출_금액,2724832,34029326,1604958,5445545,3810679,23551854,3770173,369547,1842865,5919008,...,137554326,0,3260408,194465067,29739178,11388117,46144242,12676409,14301724,83976438
연령대_40_매출_금액,0,8219377,915739,1281305,6738272,13391302,0,995315,5784546,2956460,...,110366961,0,5236046,112150047,15264827,18953022,40548964,15245431,5115517,41388194
연령대_50_매출_금액,13673767,7853565,0,0,4159712,24010024,0,1527462,2296267,2966041,...,95574245,3287672,5870155,100581336,17633259,19136736,62151484,7852159,931035,43791177
연령대_60_이상_매출_금액,500186,2786502,0,0,1699361,0,1860283,0,4855801,10092749,...,65602289,0,2738773,48009233,7211796,14352487,9432886,6968656,879311,21503173
주중_매출_건수,176,1757,32,89,244,1393,148,35,248,381,...,37403,8,3937,81322,18733,7493,52425,7306,2405,44099
주말_매출_건수,32,379,8,64,61,538,25,20,132,167,...,8187,8,1167,30290,3352,4125,22551,3362,2276,23397
월요일_매출_건수,73,286,0,0,7,403,49,10,0,86,...,6583,0,648,15175,3374,1233,10575,1195,723,9088
화요일_매출_건수,0,364,5,0,18,144,25,10,72,84,...,7609,0,809,16332,3858,1381,11518,1417,465,8147
수요일_매출_건수,49,457,6,25,46,390,0,0,15,49,...,7870,0,780,15898,3471,1427,11110,1162,518,8999
목요일_매출_건수,36,391,12,38,47,174,74,0,58,65,...,7920,0,771,16453,4126,1463,9025,1770,0,8312
금요일_매출_건수,18,259,9,26,126,282,0,15,103,97,...,7421,8,929,17464,3904,1989,10197,1762,699,9553
토요일_매출_건수,14,284,6,38,52,227,25,20,117,120,...,5586,8,762,17754,1897,1393,11167,1962,1112,12548
일요일_매출_건수,18,95,2,26,9,311,0,0,15,47,...,2601,0,405,12536,1455,2732,11384,1400,1164,10849
시간대_건수~06_매출_건수,0,0,0,0,0,0,0,0,0,0,...,141,0,0,568,0,0,5781,0,0,0
시간대_건수~11_매출_건수,0,5,1,0,0,0,0,0,0,0,...,8363,0,1681,18867,3996,3171,4678,1945,724,12437
시간대_건수~14_매출_건수,56,264,2,26,36,329,0,10,87,43,...,18583,0,1490,34764,9415,5034,14949,3348,1888,18780
시간대_건수~17_매출_건수,39,562,14,50,37,696,98,20,117,150,...,10000,8,805,24152,4898,2546,17765,2821,1708,17569
시간대_건수~21_매출_건수,86,1270,14,64,196,798,25,20,161,345,...,5909,8,700,27248,3522,811,22056,2205,361,16780
시간대_건수~24_매출_건수,27,35,9,13,36,108,50,5,15,10,...,2594,0,428,6013,254,56,9747,349,0,1930
남성_매출_건수,0,59,0,13,4,199,74,5,44,15,...,19218,0,3037,52597,10128,4239,37372,5054,1811,33303
여성_매출_건수,208,2077,40,140,301,1732,99,50,336,533,...,21788,16,1986,56542,11463,7016,37498,5440,2870,33800
연령대_10_매출_건수,0,0,0,0,0,54,0,0,0,10,...,187,0,34,1942,1383,41,6632,212,0,1141
연령대_20_매출_건수,56,715,8,52,79,922,74,10,159,116,...,8608,0,1108,38013,9058,1539,45799,2459,1966,29609
연령대_30_매출_건수,21,995,28,88,28,459,50,10,30,116,...,12008,0,750,30881,4087,2107,6409,2483,1784,16899
연령대_40_매출_건수,0,236,5,13,68,204,0,20,73,98,...,8376,0,1080,18662,2470,2831,5767,2900,672,8442
연령대_50_매출_건수,123,157,0,0,91,292,0,15,45,89,...,6452,16,1333,14280,3224,2696,9168,1459,155,8130
연령대_60_이상_매출_건수,8,33,0,0,39,0,49,0,73,119,...,5372,0,720,5358,1369,2037,1094,980,104,2883

## 4. 유동인구수 데이터 전처리
- 2019~2022 유동인구수 데이터만 남기고 2023년도꺼는 삭제한 데이터셋 만들기

In [8]:
# 유동인구수 파일 읽어오기, 한글csv file이므로 encoding cp949
# 그런데 유동인구수 파일에는 2023년 3분기 데이터셋이 있음을 확인함.
moving_people = pd.read_csv('./data/moving_people.csv', encoding='cp949')
moving_people

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20233,U,관광특구,3001496,강남 마이스 관광특구,116820,56546,60274,9741,24430,...,28982,24541,6292,16713,17686,18378,18560,18293,14662,12527
1,20233,U,관광특구,3001495,잠실 관광특구,4005509,1937145,2068365,413439,892838,...,633309,864839,465448,566137,566857,573760,570159,579731,595722,553142
2,20233,U,관광특구,3001494,종로?청계 관광특구,8353018,4439304,3913714,321655,1531086,...,1773540,1659889,647989,1344871,1344464,1353279,1316337,1316317,962386,715364
3,20233,U,관광특구,3001493,동대문패션타운 관광특구,3189182,1510236,1678946,173200,566457,...,480423,562444,384970,505715,509594,510428,496596,464684,354613,347552
4,20233,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,6822274,3317776,3504498,284079,1188425,...,1665421,1296312,342464,1117683,1129837,1153089,1116744,1090865,678392,535663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31341,20191,A,골목상권,3110005,세검정,129171,55368,73803,19624,15305,...,13667,21367,20706,18686,18746,18727,18736,18576,17782,17918
31342,20191,A,골목상권,3110004,대신고등학교,495628,226246,269381,94335,57494,...,70258,94736,65414,69892,70158,71562,71577,70647,70556,71236
31343,20191,A,골목상권,3110003,세검정초등학교,706686,310470,396215,128431,82037,...,74478,96768,85012,100783,100429,100067,99815,98912,102760,103921
31344,20191,A,골목상권,3110002,독립문역 1번,540585,246868,293717,96885,65609,...,75590,96631,70361,76301,77283,79044,78826,78583,75041,75508
31345,20191,A,골목상권,3110001,이북5도청사,155680,68432,87248,27743,15216,...,17671,22780,19199,21722,21682,21627,21636,21604,23276,24132

In [9]:
# 유동인구수 데이터셋은 2023년도의 데이터도 있으므로 다른 데이터셋과 맞추기 위해 2019~2022만 남겨놓고 2023을 전부 삭제해야함
# 기준_년분기_코드 중에 '20233' 행 존재 확인하기

moving_people[moving_people['기준_년분기_코드'] == 20233]

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
0,20233,U,관광특구,3001496,강남 마이스 관광특구,116820,56546,60274,9741,24430,...,28982,24541,6292,16713,17686,18378,18560,18293,14662,12527
1,20233,U,관광특구,3001495,잠실 관광특구,4005509,1937145,2068365,413439,892838,...,633309,864839,465448,566137,566857,573760,570159,579731,595722,553142
2,20233,U,관광특구,3001494,종로?청계 관광특구,8353018,4439304,3913714,321655,1531086,...,1773540,1659889,647989,1344871,1344464,1353279,1316337,1316317,962386,715364
3,20233,U,관광특구,3001493,동대문패션타운 관광특구,3189182,1510236,1678946,173200,566457,...,480423,562444,384970,505715,509594,510428,496596,464684,354613,347552
4,20233,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,6822274,3317776,3504498,284079,1188425,...,1665421,1296312,342464,1117683,1129837,1153089,1116744,1090865,678392,535663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1644,20233,A,골목상권,3110005,세검정,110053,49414,60639,22217,9713,...,12468,17785,15014,15942,15859,15811,15695,15593,15524,15628
1645,20233,A,골목상권,3110004,대신고등학교,642932,298259,344674,123865,75286,...,91388,125700,80105,92747,93200,92953,91929,91969,90272,89864
1646,20233,A,골목상권,3110003,세검정초등학교,552786,250919,301867,123081,60841,...,47678,67875,71892,79800,77901,77674,77580,77442,79930,82458
1647,20233,A,골목상권,3110002,독립문역 1번,547929,244018,303911,102436,62836,...,75714,97709,64942,79498,80036,79966,79213,78982,76009,74227
1648,20233,A,골목상권,3110001,이북5도청사,126315,55200,71114,21508,12855,...,14749,21717,16892,17519,17470,17507,17519,17501,19135,19661

In [10]:
# 전체 유동인구 수 데이터셋에서 20231, 20232, 20233 행 삭제
moving_people.drop(moving_people[moving_people['기준_년분기_코드'] == 20231].index, axis=0, inplace=True)
moving_people.drop(moving_people[moving_people['기준_년분기_코드'] == 20232].index, axis=0, inplace=True)
moving_people.drop(moving_people[moving_people['기준_년분기_코드'] == 20233].index, axis=0, inplace=True)

# 합친 파일 저장
moving_people.to_csv('../gentrification/data_finish/moving_people_finish.csv', index=False)
moving_people

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_유동인구_수,남성_유동인구_수,여성_유동인구_수,연령대_10_유동인구_수,연령대_20_유동인구_수,...,시간대_14_17_유동인구_수,시간대_17_21_유동인구_수,시간대_21_24_유동인구_수,월요일_유동인구_수,화요일_유동인구_수,수요일_유동인구_수,목요일_유동인구_수,금요일_유동인구_수,토요일_유동인구_수,일요일_유동인구_수
4947,20224,U,관광특구,3001496,강남 마이스 관광특구,113561,56267,57295,8423,23526,...,27583,24323,6411,15349,17220,18047,18597,18288,13967,12091
4948,20224,U,관광특구,3001495,잠실 관광특구,4179934,2015767,2164168,490222,895245,...,692222,918306,473577,571728,588228,595830,598401,615406,633869,576473
4949,20224,U,관광특구,3001494,종로?청계 관광특구,8657826,4693188,3964638,334742,1500979,...,1861965,1729022,685015,1272457,1381468,1386192,1396528,1396973,1047401,776808
4950,20224,U,관광특구,3001493,동대문패션타운 관광특구,3418870,1617046,1801825,182494,618819,...,512176,587790,412248,520582,540938,546081,547095,512377,377450,374347
4951,20224,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,7629595,3717728,3911867,365427,1301955,...,1851308,1478804,408233,1103048,1241705,1251450,1267499,1240066,864591,661235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31341,20191,A,골목상권,3110005,세검정,129171,55368,73803,19624,15305,...,13667,21367,20706,18686,18746,18727,18736,18576,17782,17918
31342,20191,A,골목상권,3110004,대신고등학교,495628,226246,269381,94335,57494,...,70258,94736,65414,69892,70158,71562,71577,70647,70556,71236
31343,20191,A,골목상권,3110003,세검정초등학교,706686,310470,396215,128431,82037,...,74478,96768,85012,100783,100429,100067,99815,98912,102760,103921
31344,20191,A,골목상권,3110002,독립문역 1번,540585,246868,293717,96885,65609,...,75590,96631,70361,76301,77283,79044,78826,78583,75041,75508
31345,20191,A,골목상권,3110001,이북5도청사,155680,68432,87248,27743,15216,...,17671,22780,19199,21722,21682,21627,21636,21604,23276,24132

In [11]:
moving_people.shape

(26399, 27)

In [12]:
moving_people.transpose()

,4947,4948,4949,4950,4951,4952,4953,4954,4955,4956,...,31336,31337,31338,31339,31340,31341,31342,31343,31344,31345
기준_년분기_코드,20224,20224,20224,20224,20224,20224,20224,20224,20224,20224,...,20191,20191,20191,20191,20191,20191,20191,20191,20191,20191
상권_구분_코드,U,U,U,U,U,U,R,R,R,R,...,A,A,A,A,A,A,A,A,A,A
상권_구분_코드_명,관광특구,관광특구,관광특구,관광특구,관광특구,관광특구,전통시장,전통시장,전통시장,전통시장,...,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권
상권_코드,3001496,3001495,3001494,3001493,3001492,3001491,3130327,3130326,3130325,3130324,...,3110010,3110009,3110008,3110007,3110006,3110005,3110004,3110003,3110002,3110001
상권_코드_명,강남 마이스 관광특구,잠실 관광특구,종로?청계 관광특구,동대문패션타운 관광특구,명동 남대문 북창동 다동 무교동 관광특구,이태원 관광특구,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",고덕 골목형상점가,명일전통시장,길동복조리시장,...,평창동서측,자하문터널,배화여자대학교(박노수미술관),사직공원(한국사회과학도서관),부암동주민센터,세검정,대신고등학교,세검정초등학교,독립문역 1번,이북5도청사
총_유동인구_수,113561,4179934,8657826,3418870,7629595,2161642,62192,147922,296251,555117,...,243528,188048,1577188,581385,21363,129171,495628,706686,540585,155680
남성_유동인구_수,56267,2015767,4693188,1617046,3717728,1085212,29346,68449,130055,251495,...,100741,87427,672613,257684,9858,55368,226246,310470,246868,68432
여성_유동인구_수,57295,2164168,3964638,1801825,3911867,1076430,32848,79473,166196,303620,...,142787,100622,904573,323701,11505,73803,269381,396215,293717,87248
연령대_10_유동인구_수,8423,490222,334742,182494,365427,141845,2326,29457,53697,86062,...,36996,26330,290718,121015,3160,19624,94335,128431,96885,27743
연령대_20_유동인구_수,23526,895245,1500979,618819,1301955,531363,9614,13415,30849,61442,...,24990,24437,206254,63921,2691,15305,57494,82037,65609,15216
연령대_30_유동인구_수,31283,996787,1638219,818283,1839034,530575,15415,23437,39736,80348,...,28267,23955,233519,77526,2621,16144,59380,73805,57402,15009
연령대_40_유동인구_수,25479,695561,1618642,662903,1667878,365423,13196,27541,47588,86276,...,34959,29044,293151,95159,3316,19331,76132,105873,82927,22233
연령대_50_유동인구_수,14310,514816,1555937,526843,1216256,267728,10194,20258,44109,85148,...,42198,30674,207190,77020,3450,22581,70175,115206,79671,25184
연령대_60_이상_유동인구_수,10540,587304,2009307,609528,1239044,324707,11448,33816,80272,155842,...,76118,53609,346356,146747,6127,36187,138113,201333,158091,50295
시간대_00_06_유동인구_수,6959,681051,903657,701521,481664,425346,14409,36792,56199,159055,...,62631,54435,501993,173836,5389,36058,98305,210576,112031,43176
시간대_06_11_유동인구_수,21446,759708,1653054,683446,1556366,381950,12470,32952,55637,110072,...,50534,39609,341905,119944,4703,23771,99231,160155,112449,34450
시간대_11_14_유동인구_수,26838,655070,1825114,521687,1853219,301082,9327,17676,40958,62544,...,28208,21102,171260,61636,2528,13601,67684,79695,73521,18405
시간대_14_17_유동인구_수,27583,692222,1861965,512176,1851308,327875,8529,17532,43071,61796,...,27821,20123,152772,57946,2496,13667,70258,74478,75590,17671
시간대_17_21_유동인구_수,24323,918306,1729022,587790,1478804,442474,9368,24725,62570,88188,...,40837,27598,207796,86162,3515,21367,94736,96768,96631,22780
시간대_21_24_유동인구_수,6411,473577,685015,412248,408233,282916,8089,18245,37817,73460,...,33498,25180,201462,81860,2734,20706,65414,85012,70361,19199
월요일_유동인구_수,15349,571728,1272457,520582,1103048,284765,9966,21245,41788,80137,...,35057,26815,226587,81832,2935,18686,69892,100783,76301,21722
화요일_유동인구_수,17220,588228,1381468,540938,1241705,280562,10389,21160,41824,79512,...,35276,26669,226244,80080,2971,18746,70158,100429,77283,21682
수요일_유동인구_수,18047,595830,1386192,546081,1251450,285830,10370,21093,42288,78566,...,35041,27046,225651,81574,2953,18727,71562,100067,79044,21627
목요일_유동인구_수,18597,598401,1396528,547095,1267499,293022,10369,21445,40898,78555,...,35103,26286,227278,80670,3007,18736,71577,99815,78826,21636
금요일_유동인구_수,18288,615406,1396973,512377,1240066,321708,9164,21322,43584,77895,...,34357,26015,222586,81052,2988,18576,70647,98912,78583,21604
토요일_유동인구_수,13967,633869,1047401,377450,864591,372454,5673,20927,42785,79492,...,34219,27548,222856,85622,3228,17782,70556,102760,75041,23276
일요일_유동인구_수,12091,576473,776808,374347,661235,323301,6263,20731,43084,80962,...,34475,27671,225987,90555,3282,17918,71236,103921,75508,24132